#!/bin/bash

VER=5.3.15
cd $XTERN_ROOT/apps/bdb_rep
rm -rf db-$VER perf install statis-benchmarks
tar zxvf $APPS_DIR/sys/db-$VER.tar.gz
tar zxvf $APPS_DIR/sys/bdb-perf.tar.gz

# Build bdb.
cd db-$VER/build_unix
# The "--with-mutex=POSIX/pthreads" is a must, otherwise the __db_pthread_mutex_lock() will not be compiled into the library and few mutexes will be invoked.
../dist/configure CFLAGS="-O3 -g" CXXFLAGS="-O3 -g" --enable-posixmutexes --with-mutex=POSIX/pthreads --prefix=$XTERN_ROOT/apps/bdb_rep/install
make && make install

# Build perf benchmark.
cd $XTERN_ROOT/apps/bdb_rep/perf
patch -p1 < ../fix-perf.patch
make
mv t $XTERN_ROOT/apps/bdb_rep/perf-test

# Build statis benchmark.
cd $XTERN_ROOT/apps/bdb_rep/
tar zxvf statis-benchmarks.tar.gz
cd statis-benchmarks
patch -p1 < ../fix-statis-benchmarks.patch
cd berkeleyDB
make
mv bdbHashThreaded $XTERN_ROOT/apps/bdb_rep/


