#!/bin/bash

cd $XTERN_ROOT/apps/bdb_rep
rm -rf out* serializer.log TXN
mkdir TXN
INIT_ENV_CMD="rm -rf TXN/*"
APP=$XTERN_ROOT/apps/bdb_rep/bench3n
INPUT="-c 300000 -t 2 -nosynctxn -logbufsize 100 -partition 8 -n 3000 TXN"                  # 2 child threads, etc. Refer to: http://libdb.wordpress.com/3n1/
echo "Running $APP $INPUT ..."

# Run with xtern and draw time chart.
$INIT_ENV_CMD;
LD_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so time $APP $INPUT
mv out out-rr
# Since in this bdb local.options, we do not start idle thread, so we must keep tid1.
$XTERN_ROOT/eval/draw-time-chart.pl ./out-rr --keep-tid1
mv time-chart.txt rr-time-chart.txt

sleep 2;

# Run non-det and draw time chart.
$INIT_ENV_CMD;
LD_PRELOAD=$XTERN_ROOT/eval/rand-intercept/rand-intercept.so time $APP $INPUT
mv out out-random
$XTERN_ROOT/eval/draw-time-chart.pl ./out-random
mv time-chart.txt random-time-chart.txt

