#!/bin/bash

cd $XTERN_ROOT/apps/bdb_rep
rm -rf out* data* rep*.log
mkdir data1
mkdir data2
mkdir data3
./gen-input | ./rep_mgr -M -h data1 -l 127.0.0.1:10001 -r 127.0.0.1:10002 -r 127.0.0.1:10003 > rep1.log 2>&1 &
sleep 20
./gen-input | ./rep_mgr -C -h data2 -l 127.0.0.1:10002 -r 127.0.0.1:10001 -r 127.0.0.1:10003 > rep2.log 2>&1 &
sleep 20
./gen-input | ./rep_mgr -C -h data3 -l 127.0.0.1:10003 -r 127.0.0.1:10001 -r 127.0.0.1:10002 > rep3.log 2>&1 &
sleep 20
ps -a | grep rep_mgr
killall -9 rep_mgr

