// DO NOT EDIT -- automatically generated by ./gen-path-slicer-opt.pl
// from path_slicer.default.options


// stop being C compatible, to simplify things.  The entire code base 
// is in C++ now, except the kernel drivers.  Can always create a C interface 
// if need be.

#ifndef __path_slicer_OPTIONS_H
#define __path_slicer_OPTIONS_H

extern int __tern_path_slicer__aaol_dbg_level;
extern int __tern_path_slicer__do_inter_thread_slicing;
extern int __tern_path_slicer__do_intra_thread_slicing;
extern int __tern_path_slicer__intra_thread_slicing_start_index;
extern int __tern_path_slicer__print_debug_info;
extern int __tern_path_slicer__slicing_mode;


#endif

