LEVEL := ../../

TESTNAME := recorder
USEDLIBS := recaccess.a recruntime.a commonruntime.a
LINK_COMPONENTS := support

include $(LEVEL)/Makefile.config
include $(LLVM_SRC_ROOT)/unittests/Makefile.unittest
