LEVEL := ../../

TESTNAME := recorder
USEDLIBS := recorder-runtime.a
LINK_COMPONENTS := support

include $(LEVEL)/Makefile.config
include $(LLVM_SRC_ROOT)/unittests/Makefile.unittest

CXXFLAGS += -I$(PROJ_SRC_ROOT)
