# -*- Makefile -*-

include $(LEVEL)/Makefile.config

# Include LLVM's Master Makefile rules.
include $(LLVM_SRC_ROOT)/Makefile.rules

# Emit a warning if can't find llvm-config 
LLVMBuildMode := $(shell $(LLVM_CONFIG) --build-mode)
ifeq ($(strip $(LLVMBuildMode)),)
  $(error Unable to find llvm-config. \
   Build Mode ($(BuildMode)) must be the same as LLVM Build Mode.)
endif
