LEVEL=../
include $(LEVEL)/Makefile.common

clean:
	-killall aget -q

eval: prepare
#	$(EXE_PREFIX) ./aget -f -n 1 http://www.cs.columbia.edu/~huayang/files/demeter.pdf
	$(EXE_PREFIX) ./aget -f -n 1 http://www.cs.columbia.edu/~huayang/files/llg++

