#!/bin/bash

cd $XTERN_ROOT/apps/aget
rm -rf out* serializer.log

INIT_ENV_CMD="rm llvm-gcc-4.2-2.7.source.tgz -rf"
APP=$XTERN_ROOT/apps/aget/aget
INPUT="-f -n2 http://www.cs.columbia.edu/~heming/unlink/llvm-gcc-4.2-2.7.source.tgz"

# Run with xtern and draw time chart.
$INIT_ENV_CMD;
time LD_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so $APP $INPUT
mv out out-rr
$XTERN_ROOT/eval/draw-time-chart.pl ./out-rr
mv time-chart.txt rr-time-chart.txt

sleep 2;

# Run non-det and draw time chart.
$INIT_ENV_CMD;
time LD_PRELOAD=$XTERN_ROOT/eval/rand-intercept/rand-intercept.so $APP $INPUT
mv out out-random
$XTERN_ROOT/eval/draw-time-chart.pl ./out-random
mv time-chart.txt random-time-chart.txt

