#!/bin/bash

#if [ -z $1 ]; then
#        # No version number
#        echo "Usage: <version number: e.g. 1.1.5>"
#        exit 1
#fi

VER=0.9.5
cd $XTERN_ROOT/apps/pbzip2
rm -rf pbzip2-$VER
if [ ! -f pbzip2-$VER.tar.gz ]; then
    wget http://pkgs.fedoraproject.org/repo/pkgs/pbzip2/pbzip2-$VER.tar.gz/94cbc6ff49a6f4df40f6b1552b613ce6/pbzip2-$VER.tar.gz
fi
tar zxvf pbzip2-$VER.tar.gz
cd pbzip2-$VER
patch -p1 < ../add-xtern-annot-0.9.5-all.patch
patch -p1 < ../add-set-base-time-annot.patch
make
mv pbzip2 ../pbzip2


#VER=1.1.5
#cd $XTERN_ROOT/apps/pbzip2
#rm -rf pbzip2-$VER
#tar zxvf $APPS_DIR/sys/pbzip2-$VER.tar.gz
#cd pbzip2-$VER
#patch -p1 < ../for-dbug-1.patch
#patch -p1 < ../add-dbg-flag.patch
#patch -p1 < ../add-xtern-annot.patch
#patch -p1 < ../add-xtern-annot-decompress.patch
#make
#mv pbzip2 ../pbzip2-v1.1.5
