#!/bin/bash

cd $XTERN_ROOT/apps/pbzip2
rm -rf out* serializer.log

ROUTINE="--compress"
if [ $1"X" != "X" ];
then
        ROUTINE=$1
fi

APP=$XTERN_ROOT/apps/pbzip2/pbzip2
if [ ! -f db-5.3.15.tar.gz ]; then
    wget http://download.oracle.com/berkeley-db/db-5.3.15.tar.gz &> /dev/null
fi
tar zxvf db-5.3.15.tar.gz &> /dev/null
gunzip -f db-5.3.15.tar.gz
mv db-5.3.15.tar input.tar

if [ $ROUTINE = "--compress" ];
then
	INPUT="-p4 -rkvf input.tar"
else
	if [ $ROUTINE = "--decompress" ];
	then
		$APP -p4 -rkvf input.tar &> /dev/null
		INPUT="-p4 -dkvf input.tar.bz2"
	else
		echo "Wrong routine: $ROUTINE, exiting...";
		exit 1;
	fi
fi

# Run with xtern and draw time chart.
LD_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so $APP $INPUT

sleep 2;

# Run non-det and draw time chart.
LD_PRELOAD=$XTERN_ROOT/eval/rand-intercept/rand-intercept.so $APP $INPUT

