#!/bin/bash

cd $XTERN_ROOT/apps/pbzip2
rm -rf out serializer.log
tar cvf input.tar $LLVM_ROOT/install/bin/llvm-ar &> /dev/null
LD_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so $XTERN_ROOT/apps/pbzip2/pbzip2 \
-p8 -rkvf input.tar
