#!/bin/bash

cd $XTERN_ROOT/apps/pbzip2
rm -rf out serializer.log
tar cvf input.tar $LLVM_ROOT/install/bin/llvm-ar &> /dev/null
LD_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so $XTERN_ROOT/apps/pbzip2/pbzip2 \
-p2 -rkvf input.tar

# Draw time chart.
$XTERN_ROOT/eval/draw-time-chart.pl ./out
