#!/bin/bash

if [ "$APPS_DIR" = "" ]; then
	echo '$APPS_DIR not defined, do `export APPS_DIR=`'
	exit 1
fi

VER=104

cd $XTERN_ROOT/apps/libpaxos

# remove previous build
rm -rf ringpaxos-src-rev$VER
unzip $APPS_DIR/sys/ringpaxos-src-rev$VER.zip
rm -rf __MACOSX

tar zxvf $APPS_DIR/sys/libevent-1.4.14b-stable.tar.gz
# install libevent
cd libevent-1.4.14b-stable
./configure --prefix=$XTERN_ROOT/apps/libpaxos/
make
make install

# install bdb
cd $APPS_DIR/bdb
./mk
