#!/bin/bash

set -e

# default value
default_nthreads=8
default_repeat=10

ROOT=`pwd`

if [ ! -d $XTERN_ROOT ]; then
	echo "XTERN_ROOT is not defined"
	exit 1
fi

PARSEC=$XTERN_ROOT/apps/parsec

if [ ! -d $PARSEC/parsec-2.0 ]; then
	echo "please run 'setup-parsec' first"
	exit 1
fi

# Linking log
if [ ! -d $PARSEC/log ]; then
    mkdir -p $PARSEC/log
fi
rm -rf $PARSEC/parsec-2.0/log
ln -s $PARSEC/log $PARSEC/parsec-2.0/log

NTHREADS=$1
if [ -z $NTHREADS ]; then
    echo "setting # of threads to default ($default_nthreads)"
    NTHREADS=$default_nthreads
fi

REPEAT=$2
if [ -z $REPEAT ]; then
    echo "setting # of repeats to default ($default_repeat)"
    REPEAT=$default_repeat
fi

LOG=$PARSEC/run$(date +"%y%j%H%m%N").log

function bench {
    TEST=$1
    INPUT=$2
    CONFIG=$3
   
    eval cmd="\"${PARSEC}/parsec-2.0/bin/parsecmgmt -a run -p ${TEST} -i ${INPUT} -c ${CONFIG} -n ${NTHREADS} -d ${PARSEC}\""
    
    for ((i=0;i<$REPEAT;i++))
    do
        ($cmd 2>&1)
    done
}

bench blackscholes	simlarge	gcc
bench bodytrack		simlarge	gcc
bench canneal		simlarge	gcc
bench dedup		simlarge	gcc
bench facesim		simlarge	gcc
bench ferret		simlarge	gcc
bench fluidanimate	simlarge	gcc
bench freqmine		simlarge	gcc # freqmine uses OpenMP
bench streamcluster	simlarge	gcc
bench raytrace		simlarge	gcc
bench swaptions		simlarge	gcc
bench vips		simlarge	gcc
bench x264		simlarge	gcc

cd $ROOT
echo "Done!"
