#!/bin/bash

VER=2.4.33
APP_DIR=$XTERN_ROOT/apps/ldap/
cd $APP_DIR
rm -rf install openldap-$VER
tar zxvf $APPS_DIR/sys/openldap-$VER.tgz

# Build.
cd openldap-$VER
patch -p1 < ../add-resp-to-mtread.patch
mkdir obj
cd obj
CFLAGS="-g -O0" CXXFLAGS="-g -O0" ../configure --prefix=$XTERN_ROOT/apps/ldap/install
make -j4
make install

# We use this one because it has debug symbols.
cd $APP_DIR
ln -s $APP_DIR/xtern-test-mt-hot $APP_DIR/openldap-$VER/tests/scripts/xtern-test-mt-hot
ln -s $APP_DIR/local.options $APP_DIR/openldap-$VER/obj/tests/local.options
ln -s $APP_DIR/openldap-$VER/obj/servers/slapd/slapd $APP_DIR/install/libexec/slapd.x86
cp $APP_DIR/install/etc/openldap/slapd.conf $APP_DIR/install/etc/openldap/slapd.conf.bak
cp slapd.conf.template $APP_DIR/install/etc/openldap/slapd.conf

# Add benchmark.
cd openldap-$VER
patch -p1 < ../only-xtern-test-mt-hot.patch
patch -p1 < ../only-run-bdb-tests.patch
cd $APP_DIR

ln -s $APP_DIR/openldap-$VER/obj/servers/slapd/slapd
ln -s $APP_DIR/openldap-$VER/obj/tests/progs/slapd-mtread
