#
# Relative path to the top of the source tree.
#
LEVEL := ../..

# x86 archive
LIBRARYNAME := recorder-runtime
BUILD_ARCHIVE := 1

# bc module
MODULE_NAME := recorder-runtime

include $(LEVEL)/Makefile.common
