#
# Relative path to the top of the source tree.
#
LEVEL := ../..

# x86 archive
LIBRARYNAME := recruntime
BUILD_ARCHIVE := 1

# bc module
MODULE_NAME := recruntime

include $(LEVEL)/Makefile.common

CXXFLAGS += -g