#!/bin/bash

cd $XTERN_ROOT/apps/scf
rm -rf scf src *.x *.inpt out*
if [ ! -f Scf.tar.gz ]; then
	wget https://www.xstackwiki.com/images/1/15/Scf.tar.gz --no-check-certificate
fi
tar -xvzf Scf.tar.gz

mkdir -p src/eti
cp -rf scf/optimized/openmp/* src/
patch -p0 < add-xtern-annot.patch

ARCH=`uname -m`
GCCLIB=""
if [ "$ARCH" == "x86_64" ]; then
  GCCLIB="$XTERN_ROOT/apps/openmp/install/lib64"
else
  GCCLIB="$XTERN_ROOT/apps/openmp/install/lib"
fi

ln -s $GCCLIB/../lib/gcc/*/4.5.4/libgcc.a src/ &>/dev/null
ln -s $GCCLIB/libgomp.a src/ &> /dev/null
ln -s $GCCLIB/libstdc++.a src/ &> /dev/null
pushd src
make
popd
ln -s src/scf.x .
ln -s scf/optimized/serial/be.inpt .

