#!/bin/bash

cd $XTERN_ROOT/apps/scf
rm -rf out* serializer.log

#Run with xtern
time LD_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so ./scf.x

#Run non-det

#time LD_PRELOAD=$XTERN_ROOT/eval/rand-intercept/rand-intercept.so ./scf.x
time ./scf.x
