#
# Relative path to the top of the source tree.
#
LEVEL := ..

#
# List all of the subdirectories that we will compile.
#
DIRS := common instr runtime analysis path-slicer

include $(LEVEL)/Makefile.common
