// RUN: %srcroot/test/runtime/run-scheduler-test.py %s -gxx "%gxx" -llvmgcc "%llvmgcc" -projbindir "%projbindir" -ternruntime "%ternruntime" -ternannotlib "%ternannotlib"  -ternbcruntime "%ternbcruntime"

#include <sys/time.h>
#include <time.h>
#include <assert.h>
#include <pthread.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>

volatile int done = 0;
pthread_mutex_t mu = PTHREAD_MUTEX_INITIALIZER;

void* thread_func(void*) {
  for(int i=0; i<10; ++i) {
    pthread_mutex_lock(&mu);
    pthread_mutex_unlock(&mu);
    pthread_mutex_lock(&mu);
    pthread_mutex_unlock(&mu);
  }
  done = 1;
}

void test(int sleep_type) {
  pthread_t th;
  struct timespec t = {1, 1};

  done = 0;
  int ret = pthread_create(&th, NULL, thread_func, NULL);
  assert(!ret && "pthread_create() failed!");

  while(!done) {
    switch(sleep_type) {
    case 0: sleep(1); break;
    case 1: usleep(1); break;
    case 2: nanosleep(&t, NULL); break;
    default: abort();
    }
  }
  pthread_join(th, NULL);
}

int main(int argc, char *argv[], char *env[]) {
  test(0);
  printf("sleep() test done\n");
  test(1);
  printf("usleep() test done\n");
  test(2);
  printf("nanosleep() test done\n");
}



// CHECK indicates expected output checked by FileCheck; auto-generated by appending -gen to the RUN command above.
// CHECK:      sleep() test done
// CHECK-NEXT: usleep() test done
// CHECK-NEXT: nanosleep() test done
