// RUN: %srcroot/test/runtime/run-scheduler-test.py %s -gxx "%gxx" -llvmgcc "%llvmgcc" -projbindir "%projbindir" -ternruntime "%ternruntime" -ternannotlib "%ternannotlib"  -ternbcruntime "%ternbcruntime" -nondet

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <pthread.h>
#include <netdb.h>

#define N (100)

void error(const char *msg)
{
    perror(msg);
    exit(0);
}

pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
pthread_cond_t cv = PTHREAD_COND_INITIALIZER;

void *client_thread(void *arg)
{
    int sockfd, portno, n;
    struct sockaddr_in serv_addr;
    struct hostent *server;

    char buffer[256];

    portno = *((int*)arg);
    sockfd = socket(AF_INET, SOCK_STREAM, 0);
    if (sockfd < 0)
        error("ERROR opening socket");
    server = gethostbyname("127.0.0.1");
    if (server == NULL) {
        fprintf(stderr,"ERROR, no such host\n");
        exit(0);
    }
    bzero((char *) &serv_addr, sizeof(serv_addr));
    serv_addr.sin_family = AF_INET;
    bcopy((char *)server->h_addr,
         (char *)&serv_addr.sin_addr.s_addr,
         server->h_length);
    serv_addr.sin_port = htons(portno);
    sleep(1);
    if (connect(sockfd,(struct sockaddr *) &serv_addr,sizeof(serv_addr)) < 0)
        error("ERROR connecting");
    bzero(buffer,256);
    const char *hello = "hello world.";
    strcpy(buffer, hello);
    for(int i=0; i<N; ++i) {
      n = write(sockfd,buffer,strlen(buffer));
      if (n < 0)
        error("ERROR writing to socket");
      bzero(buffer,256);
      n = read(sockfd,buffer,255);
      if (n < 0)
        error("ERROR reading from socket");
      printf("%s\n",buffer);
    }
    close(sockfd);
    return 0;
}

int main(int argc, char *argv[])
{
     int sockfd, newsockfd, portno;
     socklen_t clilen;
     char buffer[256];
     struct sockaddr_in serv_addr, cli_addr;
     int n;
     pthread_t th;
     int optval = 1;

     srand(time(NULL));
     portno = 20000 + rand()%1000;
     sockfd = socket(AF_INET, SOCK_STREAM, 0);
     if (sockfd < 0)
        error("ERROR opening socket");

     setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof optval);
     bzero((char *) &serv_addr, sizeof(serv_addr));
     serv_addr.sin_family = AF_INET;
     serv_addr.sin_addr.s_addr = INADDR_ANY;
     serv_addr.sin_port = htons(portno);
     if (bind(sockfd, (struct sockaddr *) &serv_addr,
              sizeof(serv_addr)) < 0)
              error("ERROR on binding");
     listen(sockfd,5);
     pthread_create(&th, NULL, client_thread, (void*) &portno);
     clilen = sizeof(cli_addr);
     newsockfd = accept(sockfd,
                 (struct sockaddr *) &cli_addr,
                 &clilen);
     if (newsockfd < 0)
          error("ERROR on accept");
     for(int i=0; i<N; ++i) {
       bzero(buffer,256);
       n = read(newsockfd,buffer,255);
       if (n < 0)
         error("ERROR reading from socket");
       printf("Here is the message: %s\n",buffer);
       n = write(newsockfd,"I got your message",18);
       if (n < 0)
         error("ERROR writing to socket");
     }
     close(newsockfd);
     close(sockfd);
     pthread_join(th, NULL);
     printf("test done\n");
     return 0;
}
// CHECK indicates expected output checked by FileCheck; auto-generated by appending -gen to the RUN command above.
// CHECK:      Here is the message: hello world.
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: Here is the message: I got your message
// CHECK-NEXT: I got your message
// CHECK-NEXT: test done
