#!/bin/bash

cd $XTERN_ROOT/apps/pfscan
rm -rf out* serializer.log

INIT_ENV_CMD=""
APP=$XTERN_ROOT/apps/pfscan/pfscan
INPUT="-n2 -v -d -d return $XTERN_ROOT/apps/pfscan/pfscan-1.0/"

# Run with xtern and draw time chart.
$INIT_ENV_CMD;
LD_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so $APP $INPUT
mv out out-rr
$XTERN_ROOT/eval/draw-time-chart.pl ./out-rr
mv time-chart.txt rr-time-chart.txt

sleep 2;

# Run non-det and draw time chart.
$INIT_ENV_CMD;
LD_PRELOAD=$XTERN_ROOT/eval/rand-intercept/rand-intercept.so $APP $INPUT
mv out out-random
$XTERN_ROOT/eval/draw-time-chart.pl ./out-random
mv time-chart.txt random-time-chart.txt

