#!/bin/bash

#
# Copyright (c) 2013,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

llvm_debug="ENABLE_OPTIMIZED=0"
build_mode="Debug"
for arg in "$@"; do
    if test "$arg" = "--optimized"; then
        llvm_debug="ENABLE_OPTIMIZED=1"
        build_mode="Release"
    fi
done

llvmver="2.7"
gccver="4.2-$llvmver"
arch=`uname -m`
timeout=1200
sendmail="/usr/sbin/sendmail"
toaddr="dmt-dev@lists.cs.columbia.edu"
xtern_git="git@repair.cs.columbia.edu:xtern"

# toaddr="junfeng@cs.columbia.edu"
# xtern_git="/home/junfeng/work/xtern"

#testdir=`date +%F`
testdir="/tmp/xtern-nightly-test-$build_mode"
rm -rf $testdir
mkdir -p $testdir
cd $testdir
testdir=$PWD
log=$testdir/out.txt

export LLVM_ROOT="$testdir/llvm"
export PATH="$PATH:$LLVM_ROOT/install/bin:$LLVM_ROOT/scripts"
export XTERN_ROOT="$testdir/xtern"

# # build llvm
git clone git@repair.cs.columbia.edu:llvm
cd $LLVM_ROOT
mkdir -p install

wget http://llvm.org/releases/2.7/llvm-gcc$gccver-$arch-linux.tar.bz2
tar xjvf llvm-gcc$gccver-$arch-linux.tar.bz2
(cd llvm-gcc$gccver-$arch-linux; tar cf - .) |(cd install; tar xvf -)

wget http://llvm.org/releases/$llvmver/llvm-$llvmver.tgz
tar xzvf llvm-$llvmver.tgz
if test "$llvmver" = "2.7" ; then
    cd llvm-$llvmver
    patch -p1 < ../fix-cstddef-2.7.patch
    cd ../
fi
mkdir -p llvm-obj
cd llvm-obj
../llvm-$llvmver/configure --prefix="$LLVM_ROOT/install" --enable-targets=$arch
make $llvm_debug -j2
make $llvm_debug install

# build llvm/common
cd $LLVM_ROOT
mkdir common-obj
cd common-obj
../common/configure --with-llvmsrc="$LLVM_ROOT/llvm-$llvmver" \
                    --with-llvmobj="$LLVM_ROOT/llvm-obj"      \
                    --prefix="$LLVM_ROOT/install"
make $llvm_debug
make $llvm_debug install

# build xtern
cd $testdir
git clone $xtern_git
cd $XTERN_ROOT
mkdir obj
cd obj
../configure --prefix=$XTERN_ROOT/install >> $log
make $llvm_debug  >> $log
make -C $XTERN_ROOT/dync_hook $llvm_debug BuildMode=$build_mode >> $log

# run tests
cd $XTERN_ROOT/obj
export LD_LIBRARY_PATH="$XTERN_ROOT/dync_hook" # for testing annotations
timeout $timeout make $llvm_debug check >> $log 2>&1
status=$?
if test $status != 0 ; then
    if test $status == 124 ; then
        echo "$timeout seconds have passed; killed process $pid" >> $log
    fi
    (
        echo "TO: $toaddr"
        echo "FROM: junfeng@cs.columbia.edu"
        echo "SUBJECT: xtern nightly test failed with status $status"
        cat $log
        echo "."
    ) | $sendmail $toaddr
fi
