#!/bin/bash

if [ "$APPS_DIR" = "" ]; then
	echo '$APPS_DIR not defined, do `export APPS_DIR=`'
	exit 1
fi

VER=6.8.0-4
echo ""
echo "Please make sure you have run the 'mk' in $XTERN_ROOT/apps/openmp before you build imagick."
echo ""
sleep 2
cd $XTERN_ROOT/apps/openmp/imagick
rm -rf ImageMagick-$VER install *.a
tar zxvf $APPS_DIR/sys/ImageMagick-$VER.tar.gz
ln -s $XTERN_ROOT/apps/openmp/install/lib64/libgomp.a
ln -s $XTERN_ROOT/apps/openmp/install/lib64/libstdc++.a

# compile ImageMagick
cd ImageMagick-$VER
patch -p1 < ../link-static-libgomp.patch
mkdir obj
cd obj
../configure --prefix=$XTERN_ROOT/apps/openmp/imagick/install --disable-shared --enable-static &> config.results
make
make install

# Don't know why we have to clean and recompile and then we could link in the static libgomp. Weird.
make distclean
../configure --prefix=$XTERN_ROOT/apps/openmp/imagick/install --disable-shared --enable-static &> config.results
make
make install

# TBD.

