#!/bin/bash

if [ "$APPS_DIR" = "" ]; then
	echo '$APPS_DIR not defined, do `export APPS_DIR=`'
	exit 1
fi

VER=6.8.0-4
echo ""
echo "Please make sure you have run the 'mk' in $XTERN_ROOT/apps/openmp before you build imagick."
echo ""
sleep 2
cd $XTERN_ROOT/apps/openmp/imagick
rm -rf ImageMagick-$VER install *.a
tar zxvf $APPS_DIR/sys/ImageMagick-$VER.tar.gz
ln -s $XTERN_ROOT/apps/openmp/install/lib64/libgomp.a
ln -s $XTERN_ROOT/apps/openmp/install/lib64/libstdc++.a
XTERN_ANNOT_LIB="-L$XTERN_ROOT/dync_hook -lxtern-annot"

# compile ImageMagick
cd ImageMagick-$VER
patch -p1 < ../add-convert-xtern-annot.patch
mkdir obj
cd obj

C_STATIC_LIB_GOMP="-g -O2 -static-libgcc -L$XTERN_ROOT/apps/openmp/imagick -fopenmp -lgomp"
CXX_STATIC_LIB_GOMP=$C_STATIC_LIB_GOMP
#"-static-libgcc -static-libstdc++ -D_GLIBCXX_PARALLEL -L$XTERN_ROOT/apps/openmp/imagick -fopenmp -lgomp"

CFLAGS+="$C_STATIC_LIB_GOMP -I$XTERN_ROOT/include -L$XTERN_ROOT/dync_hook -lxtern-annot" \
  CXXFLAGS+="$CXX_STATIC_LIB_GOMP -I$XTERN_ROOT/include -L$XTERN_ROOT/dync_hook -lxtern-annot" \
  LIBS+="$CXX_STATIC_LIB_GOMP -L$XTERN_ROOT/dync_hook -lxtern-annot" \
  ../configure --prefix=$XTERN_ROOT/apps/openmp/imagick/install --disable-shared --enable-static &> config.results

make V=1
make install

