#!/bin/bash

if [ "$APPS_DIR" = "" ]; then
	echo '$APPS_DIR not defined, do `export APPS_DIR=`'
	exit 1
fi

VER=6.8.0-4
echo "\n\nPlease make sure you have run the `mk` in $XTERN_ROOT/apps/openmp before you build imagick.\n\n"
sleep 2
cd $XTERN_ROOT/apps/openmp/imagick
rm -rf ImageMagick-$VER install *.a
tar zxvf $APPS_DIR/sys/ImageMagick-$VER.tar.gz
ln -s $XTERN_ROOT/apps/openmp/install/lib64/libgomp.a
ln -s $XTERN_ROOT/apps/openmp/install/lib64/libstdc++.a

# compile ImageMagick
cd ImageMagick-$VER
patch -p1 < ../link-static-libgomp.patch
mkdir obj
cd obj
../configure --prefix=$XTERN_ROOT/apps/openmp/imagick/install --disable-shared --enable-static
make
make install

make
cd ..

# TBD.
