// RUN: %srcroot/test/runtime/run-scheduler-test.py %s -gxx "%gxx" -llvmgcc "%llvmgcc" -projbindir "%projbindir" -ternruntime "%ternruntime"  -ternbcruntime "%ternbcruntime"

#include <sys/time.h>
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <assert.h>
#include <unistd.h>
#include <errno.h>

#define N (2)

void bar() {
  pthread_exit(NULL);
}

void* thread_func(void *arg) {
  bar();
}

int main(int argc, char *argv[], char *env[]) {
  int ret;
  pthread_t th[N];

  for(unsigned i=0; i<N; ++i) {
    ret  = pthread_create(&th[i], NULL, thread_func, (void*)i);
    assert(!ret && "pthread_create() failed!");
  }

  for(unsigned i=0; i<N; ++i)
    pthread_join(th[i], NULL);

  printf("calling pthread_exit(NULL)\n");
  pthread_exit(NULL);
  return 0;
}

// OUT indicates expected output checked by  FileCheck; auto-generated by appending -gen to the RUN command above.
// OUT:      calling pthread_exit(NULL)
// RR indicates expected RR schedule checked by  FileCheck; auto-generated by appending -gen to the RUN command above.
// RR:      pthread_create 1 0 0
// RR-NEXT: pthread_create 3 0 0
// RR-NEXT: pthread_join 6 0
// RR-NEXT: pthread_join 8 0
