// RUN: %srcroot/test/runtime/run-scheduler-test.py %s -gxx "%gxx" -llvmgcc "%llvmgcc" -projbindir "%projbindir" -ternruntime "%ternruntime"  -ternbcruntime "%ternbcruntime"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;

int main(int argc, char *argv[], char *env[]) {
  char buf0[64], buf1[64], buf2[64];
  sprintf(buf1, "this is a test. ");
  sprintf(buf2, "another test.");
  strcpy(buf0, buf1);
  strcat(buf0, buf2);
  printf("%s\n", buf0);
  pthread_mutex_lock(&m);
  pthread_mutex_unlock(&m);
  return 0;
}

// OUT indicates expected output checked by FileCheck; auto-generated by appending -gen to the RUN command above.
// OUT:      this is a test. another test.
// RR indicates expected RR schedule checked by FileCheck; auto-generated by appending -gen to the RUN command above.
// RR:      pthread_mutex_lock 1 0
// RR-NEXT: pthread_mutex_unlock 2 0
