// RUN: %srcroot/test/runtime/run-scheduler-test.py %s -gxx "%gxx" -llvmgcc "%llvmgcc" -projbindir "%projbindir" -ternruntime "%ternruntime"  -ternbcruntime "%ternbcruntime"

#include <sys/time.h>
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <semaphore.h>
#include <assert.h>
#include <unistd.h>
#include <errno.h>

#define N (2)

sem_t sem, another_sem;
pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;

void* sem_wait_func(void *arg) {
  char buf[64];
  int tid = (intptr_t)arg;

  for(unsigned i=0;i<10;++i)
    sched_yield();

  int ret;
  struct timespec   ts;
  struct timeval    tp;

  // test 3 different ways of sem_wait
  switch(tid % 3) {
  case 0:
    sem_wait(&sem);
    break;
  case 1:
    do{
      ret = sem_trywait(&sem);
    } while(ret!=0);
    break;
  case 2:
    do {
      gettimeofday(&tp, NULL);
      ts.tv_sec  = tp.tv_sec;
      ts.tv_nsec = tp.tv_usec * 1000 + 100;
      ret = sem_timedwait(&sem, &ts);
    } while(ret!=0);
    break;
  }

  printf("%03d WAKES UP\n", tid);
  printf("%03d POSTS\n", tid);

  sem_post(&another_sem);
}

void* sem_post_func(void *arg) {
  char buf[64];
  int tid = (intptr_t)arg;

  for(unsigned i=0;i<100;++i)
    sched_yield();

  printf("%03d POSTS\n", tid);
  sem_post(&sem);
  sem_wait(&another_sem);
  printf("%03d WAKES UP\n", tid);
}

int main(int argc, char *argv[], char *env[]) {
  int ret;
  pthread_t th[N];

  sem_init(&sem, 0, 0);
  sem_init(&another_sem, 0, 0);

  for(unsigned i=0; i<N/2; ++i) {
    ret  = pthread_create(&th[i], NULL, sem_wait_func, (void*)i);
    assert(!ret && "pthread_create() failed!");
  }

  for(unsigned i=(N+1)/2; i<N; ++i) {
    ret  = pthread_create(&th[i], NULL, sem_post_func, (void*)i);
    assert(!ret && "pthread_create() failed!");
  }

  for(unsigned i=0; i<N; ++i)
    pthread_join(th[i], NULL);

  sem_destroy(&sem);
}

// OUT indicates expected output checked by FileCheck; auto-generated by appending -gen to the RUN command above.
// OUT:      001 POSTS
// OUT-NEXT: 000 WAKES UP
// OUT-NEXT: 000 POSTS
// OUT-NEXT: 001 WAKES UP
// RR indicates expected RR schedule checked by FileCheck; auto-generated by appending -gen to the RUN command above.
// RR:      pthread_create 1 0 0
// RR-NEXT: pthread_create 3 0 0
// RR-NEXT: sem_post 5 2
// RR-NEXT: sem_wait 6 1
// RR-NEXT: sem_post 7 1
// RR-NEXT: sem_wait 8 2
// RR-NEXT: pthread_join 11 0
// RR-NEXT: pthread_join 12 0
