// RUN: %srcroot/test/runtime/run-scheduler-test.py %s -gxx "%gxx" -llvmgcc "%llvmgcc" -projbindir "%projbindir" -ternruntime "%ternruntime"  -ternbcruntime "%ternbcruntime" -nondet

#include <pthread.h>
#include <unistd.h>

pthread_mutex_t mutex;

void *myfunc(void *arg)
{
  pthread_mutex_lock(&mutex);
  pthread_mutex_unlock(&mutex);
  return NULL;
}

int main()
{
  pthread_t t;
  pthread_mutex_init(&mutex, NULL);
  pthread_create(&t, NULL, myfunc, NULL);
  if (fork() != 0) {
    wait(NULL);
    return 0;
  }
  pthread_mutex_lock(&mutex);
  pthread_mutex_unlock(&mutex);
  printf("test done\n");
  return 0;
}
// CHECK indicates expected output checked by FileCheck; auto-generated by appending -gen to the RUN command above.
// CHECK:      test done
