// RUN: %srcroot/test/runtime/run-scheduler-test.py %s -gxx "%gxx" -llvmgcc "%llvmgcc" -projbindir "%projbindir" -ternruntime "%ternruntime" -ternannotlib "%ternannotlib"  -ternbcruntime "%ternbcruntime" -nondet

// NOTE: theoretically fork() should not be mixed with threads.  However,
// in practice some real applications such as Apache do this, so we have
// to make it work ...

#include <pthread.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <stdio.h>
#include <assert.h>

pthread_mutex_t mutex;

void *myfunc(void *arg)
{
  pthread_mutex_lock(&mutex);
  pthread_mutex_unlock(&mutex);
  return NULL;
}

int main()
{
  pthread_t t;
  pthread_mutex_init(&mutex, NULL);
  pthread_create(&t, NULL, myfunc, NULL);
  int ret;
  if ((ret = fork()) > 0) {
    wait(NULL);
    printf("\ntest done by parent: pid %d, ret pid %d\n\n\n", getpid(), ret);
    return 0;
  }
  assert(ret == 0);
  printf("\ntest done start pid %d\n\n\n", getpid());
  pthread_mutex_init(&mutex, NULL);
  printf("\ntest done start2 pid %d\n\n\n", getpid());
  pthread_mutex_lock(&mutex);
  pthread_mutex_unlock(&mutex);
  printf("test done\n\n\n");
  return 0;
}
// CHECK indicates expected output checked by FileCheck; auto-generated by appending -gen to the RUN command above.
// CHECK:      test done
