#
# Relative path to the top of the source tree.
#
LEVEL := ../..

# x86 archive
LIBRARYNAME := commonruntime
BUILD_ARCHIVE := 1

# bc module
MODULE_NAME := commonruntime

include $(LEVEL)/Makefile.common
