#!/bin/bash

VER=2.4.11
JOBS=$1
cd $XTERN_ROOT/apps/redis/
if [ ! -f redis-$VER.tar.gz ]; then
    wget http://redis.googlecode.com/files/redis-$VER.tar.gz
fi
tar zxvf redis-$VER.tar.gz

cd redis-$VER

# Uncomment below redis-time.patch for experiment with dbug.
# Comment it out for experiment with xtern only.
#patch -p1 < ../redis-time.patch

# compile
if [ "$JOBS" = "" ]; then
    make FORCE_LIBC_MALLOC=yes    
else
    make FORCE_LIBC_MALLOC=yes -j $JOBS
fi


# copy redis-server and benchmark tool
cp src/redis-server ../
cp src/redis-benchmark ../
