#!/bin/bash

if [ "$APPS_DIR" = "" ]; then
	echo '$APPS_DIR not defined, do `export APPS_DIR=`'
	exit 1
fi

VER=2.4.11
JOBS=$1

cd redis-$VER

# compile
if [ "$JOBS" = "" ]; then
    make FORCE_LIBC_MALLOC=yes    
else
    make FORCE_LIBC_MALLOC=yes -j $JOBS
fi


# copy redis-server and benchmark tool
cp src/redis-server ../
cp src/redis-benchmark ../
