#!/bin/bash

if [ "$APPS_DIR" = "" ]; then
	echo '$APPS_DIR not defined, do `export APPS_DIR=`'
	exit 1
fi

if [ -z $1 ]; then
	# No version number
	echo "Usage: <version number: e.g. 2.4.11>"
	exit 1
fi
VER=$1

# remove previous build
rm -rf redis-$VER
tar zxvf $APPS_DIR/sys/redis-$VER.tar.gz

