#!/bin/bash

if [ "$APPS_DIR" = "" ]; then
	echo '$APPS_DIR not defined, do `export APPS_DIR=`'
	exit 1
fi

VER=2.4.11

# remove previous build
rm -rf redis-$VER redis-benchmark redis-server
tar zxvf $APPS_DIR/sys/redis-$VER.tar.gz

