#!/bin/bash

set -e

ROOT=`pwd`
ARCH=`uname -m`

if [ ! -d $XTERN_ROOT ]; then
	echo "XTERN_ROOT is not defined"
	exit 1
fi

if [ ! -f NPB3.3.1.tar.gz ]; then
    wget http://www.cs.columbia.edu/~heming/release/NPB3.3.1.tar.gz
fi

if [ ! -f $XTERN_ROOT/apps/openmp/install/bin/gfortran ]; then
    echo "please recompile \$XTERN_ROOT/apps/openmp/mk with fortran available"
    exit 1
fi

pushd $XTERN_ROOT/apps/npb/

# clean up
rm -rf NPB3.3.1
tar zxvf NPB3.3.1.tar.gz

pushd NPB3.3.1/NPB3.3-OMP
SYS_LIB_PATH=""
if [ "$ARCH" == "x86_64" ]; then
  ln -s $XTERN_ROOT/apps/openmp/install/lib64/libgomp.a
  ln -s $XTERN_ROOT/apps/openmp/install/lib64/libstdc++.a
  SYS_LIB_PATH="/usr/lib/x86_64-linux-gnu"
else
  ln -s $XTERN_ROOT/apps/openmp/install/lib/libgomp.a
  ln -s $XTERN_ROOT/apps/openmp/install/lib/libstdc++.a
  SYS_LIB_PATH="/usr/lib/i386-linux-gnu"
fi
popd

# Add patches.
pushd NPB3.3.1
patch -p1 < ../patch/lu.patch
patch -p1 < ../patch/annot-UA-omp-non-det.patch
popd

# make
mkdir -p NPB3.3.1/NPB3.3-OMP/bin-s
ln -s $XTERN_ROOT/apps/npb/make-small.def NPB3.3.1/NPB3.3-OMP/config/make.def
ln -s $XTERN_ROOT/apps/npb/suite-small.def NPB3.3.1/NPB3.3-OMP/config/suite.def
pushd NPB3.3.1/NPB3.3-OMP
LIBRARY_PATH=$SYS_LIB_PATH make suite
popd

mkdir -p NPB3.3.1/NPB3.3-OMP/bin-m
rm -rf NPB3.3.1/NPB3.3-OMP/config/make.def
rm -rf NPB3.3.1/NPB3.3-OMP/config/suite.def
ln -s $XTERN_ROOT/apps/npb/make-medium.def NPB3.3.1/NPB3.3-OMP/config/make.def
ln -s $XTERN_ROOT/apps/npb/suite-medium.def NPB3.3.1/NPB3.3-OMP/config/suite.def
pushd NPB3.3.1/NPB3.3-OMP
LIBRARY_PATH=$SYS_LIB_PATH make suite
popd

mkdir -p NPB3.3.1/NPB3.3-OMP/bin-l
rm -rf NPB3.3.1/NPB3.3-OMP/config/make.def
rm -rf NPB3.3.1/NPB3.3-OMP/config/suite.def
ln -s $XTERN_ROOT/apps/npb/make-large.def NPB3.3.1/NPB3.3-OMP/config/make.def
ln -s $XTERN_ROOT/apps/npb/suite-large.def NPB3.3.1/NPB3.3-OMP/config/suite.def
pushd NPB3.3.1/NPB3.3-OMP
LIBRARY_PATH=$SYS_LIB_PATH make suite
popd

rm -rf NPB3.3.1/NPB3.3-OMP/config/make.def
ln -s $XTERN_ROOT/apps/npb/make.def NPB3.3.1/NPB3.3-OMP/config/
rm -rf NPB3.3.1/NPB3.3-OMP/config/suite.def
ln -s $XTERN_ROOT/apps/npb/suite.def NPB3.3.1/NPB3.3-OMP/config/
pushd NPB3.3.1/NPB3.3-OMP
LIBRARY_PATH=$SYS_LIB_PATH make suite
popd

rm -rf ft-s mg-s sp-s lu-s bt-s is-s ep-s cg-s ua-s dc-s
rm -rf ft-m mg-m sp-m lu-m bt-m is-m ep-m cg-m ua-m dc-m
rm -rf ft-l mg-l sp-l lu-l bt-l is-l ep-l cg-l ua-l dc-l
bench=( ft mg sp lu bt is ep cg ua dc )
for i in "${bench[@]}"
do
    ln -s NPB3.3.1/NPB3.3-OMP/bin-s/$i.?.x $i-s
    ln -s NPB3.3.1/NPB3.3-OMP/bin-m/$i.?.x $i-m
    ln -s NPB3.3.1/NPB3.3-OMP/bin-l/$i.?.x $i-l
done

rm -rf ft mg sp lu bt is ep cg ua dc
bench=( ft mg sp lu bt is ep cg ua dc )
for i in "${bench[@]}"
do
    ln -s NPB3.3.1/NPB3.3-OMP/bin/$i.?.x $i
done

popd
echo "DONE!"
