#!/usr/bin/env python

import os, sys, time

if len(sys.argv) < 4:
    print >> sys.stderr, 'Usage: ' + sys.argv[0] + ' <# requests> <# of clients> <ip:port/file>'
    exit()

def extract_real_number(line):
    found = False
    num = 0
    for token in line.split():
        try:
            num = float(token)
            found = True
            break
        except ValueError:
            pass
    assert(found)
    return num

bench_res = os.popen('./ab -n ' + sys.argv[1] + ' -c ' + sys.argv[2] + ' ' + sys.argv[3])

response_time = 0
reqs_per_second = 0
for line in bench_res.readlines():
    if line.find('Requests per second') != -1:
        print >> sys.stderr, line
        reqs_per_second = extract_real_number(line)
    elif line.find('Time per request') != -1:
        print >> sys.stderr, line
        response_time = extract_real_number(line)

print reqs_per_second, response_time
time.sleep(3)
