#!/bin/sh -e

#
# Copyright (c) 2013,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

VER="2.7" # only works with llvm 2.7 for now
GCCVER="4.2-$VER"
MACHINE=`uname -m`
ROOT=$PWD

debug=1
for arg in "$@"; do
    if test "$arg" = "--optimized"; then
        debug=0
    fi
done

if test "$debug" = "1"; then
    llvm_debug="ENABLE_OPTIMIZED=0"
    gcc_debug="--enable-checking"
else
    llvm_debug="ENABLE_OPTIMIZED=1"
    gcc_debug="--disable-checking"
fi

if [ ! -e llvm-$VER.tgz ]
then
    echo "Can't find llvm source (llvm-$VER.tgz). Please download from llvm.org."
    exit 0
fi
#if [ ! -e llvm-gcc$GCCVER-$MACHINE-linux.tar.bz2 ]
#then
#    echo "Can't find llvm gcc binary (llvm-gcc$GCCVER-$MACHINE-linux.tar.bz2)."\
#         "Please download from llvm.org."
#    exit 0
#fi

# install gcc
mkdir -p install
#tar xjvf llvm-gcc$GCCVER-$MACHINE-linux.tar.bz2
(cd llvm-gcc$GCCVER-$MACHINE-linux; tar cf - .) |(cd install; tar xvf -)

# install llvm
tar xzvf llvm-$VER.tgz
mkdir -p llvm-obj
cd llvm-obj
../llvm-$VER/configure --prefix="$ROOT/install"
make $llvm_debug -j64
make $llvm_debug install
cd ..

echo "Please set environment variable LLVM_ROOT to '$ROOT'"
echo "and add '$ROOT/install/bin' and '$ROOT/scripts' to your PATH."
