#!/bin/bash

set -e

ARCH=`uname -m`
XTERN_ANNOT_LIB="-I$XTERN_ROOT/include -L$XTERN_ROOT/dync_hook -Wl,--rpath,$XTERN_ROOT/dync_hook -lxtern-annot"
VER=4.5.4
echo -e "\nWe are compiling gcc-$VER by ourselves. We hope you have installed the same version of gcc on your machine, because we are going to use some libraries of it.\n";
cd $XTERN_ROOT/apps/openmp
rm -rf gcc-$VER install *.a ex//*.a
if [ ! -f gcc-$VER.tar.gz ]; then
    wget http://ftp.gnu.org/gnu/gcc/gcc-$VER/gcc-$VER.tar.gz
fi
tar zxf gcc-$VER.tar.gz

# compile gcc
cd gcc-$VER
patch -p1 < ../patch/add-xtern-annot.patch
patch -p1 < ../patch/annot-partition-non-det.patch
patch -p1 < ../patch/add-detach.patch
mkdir obj
cd obj
CFLAGS+="$XTERN_ANNOT_LIB" ../configure \
--prefix=$XTERN_ROOT/apps/openmp/install --disable-linux-futex --enable-languages=c,c++,fortran --disable-multilib
if [ "$ARCH" == "x86_64" ]; then
  LIBRARY_PATH=/usr/lib/x86_64-linux-gnu make -j64
else
  LIBRARY_PATH=/usr/lib/i386-linux-gnu make -j64
fi
make -j64 install


# Build the random shuffle benchmark.
cd $XTERN_ROOT/apps/openmp
if [ "$ARCH" == "x86_64" ]; then
  ln -s $XTERN_ROOT/apps/openmp/install/lib64/libgomp.a
  ln -s $XTERN_ROOT/apps/openmp/install/lib64/libstdc++.a
else
  ln -s $XTERN_ROOT/apps/openmp/install/lib/libgomp.a
  ln -s $XTERN_ROOT/apps/openmp/install/lib/libstdc++.a
fi
#g++ -g  rand-shuf.cpp -o rand-serial

# Heming: we must add "-lgomp" in order to make the compilation pass.
g++ -g -static-libgcc -static-libstdc++ -D_GLIBCXX_PARALLEL -L. -fopenmp rand-shuf.cpp -o rand-para -lgomp $XTERN_ANNOT_LIB

# Build the parallel for benchmark. Heming: we must add "-lgomp" in order to make the compilation pass.
g++ -g -static-libgcc -static-libstdc++ -D_GLIBCXX_PARALLEL -L. -fopenmp examples/ex-for.cpp -o ex-for -lgomp $XTERN_ANNOT_LIB

# Build some other examples.
cd ex
if [ "$ARCH" == "x86_64" ]; then
  ln -s $XTERN_ROOT/apps/openmp/install/lib64/libgomp.a
  ln -s $XTERN_ROOT/apps/openmp/install/lib64/libstdc++.a
else
  ln -s $XTERN_ROOT/apps/openmp/install/lib/libgomp.a
  ln -s $XTERN_ROOT/apps/openmp/install/lib/libstdc++.a
fi
make
cd ..

# TBD.

