#!/bin/bash

VER=3.6
cd $XTERN_ROOT/apps/mongoose
rm -rf mongoose out
if [ ! -f mongoose-$VER.tgz ]; then
    wget http://mongoose.googlecode.com/files/mongoose-$VER.tgz
fi
tar zxvf mongoose-$VER.tgz
cd mongoose
make linux
mv mongoose ../mg-server
cd $XTERN_ROOT/apps/mongoose
rm -rf aget
ln -s $XTERN_ROOT/apps/aget/aget
